
version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data_v7:/usr/share/elasticsearch/data
    networks:
      - efk
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - efk

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx_logs:/var/log/nginx
    # 심볼릭 링크 제거하고 실제 로그 파일 생성
    command: >
      sh -c "
      rm -f /var/log/nginx/access.log /var/log/nginx/error.log &&
      touch /var/log/nginx/access.log /var/log/nginx/error.log &&
      nginx -g 'daemon off;'
      "
    networks:
      - efk
    restart: unless-stopped

  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    container_name: fluentd
    volumes:
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf:ro
      - ./logs:/var/log/host:ro
      - fluentd_buffer_v7:/tmp/fluentd-buffers
      - nginx_logs:/var/log/nginx:ro  # nginx와 직접 공유 (읽기 전용)
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      elasticsearch:
        condition: service_healthy
      nginx:
        condition: service_started
    networks:
      - efk
    restart: unless-stopped

volumes:
  elasticsearch_data_v7:
    driver: local
  fluentd_buffer_v7:
    driver: local
  nginx_logs:
    driver: local

networks:
  efk:
    driver: bridge