
logging:
  level:
    kr.co.moviearchive: DEBUG
    root: INFO
  file:
    name: ./logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p --- [%15.15t] %-40.40logger{39} : %m%n"
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p --- [%15.15t] %-40.40logger{39} : %m%n"